import { AuditParams } from '../@types/user-defined'
import { AuditClient } from '../data'

export enum Page {
  EXAMPLE_PAGE = 'EXAMPLE_PAGE',
  VIEW_INDEX_PAGE = 'VIEW_INDEX_PAGE',
  VIEW_APPOINTMENT = 'VIEW_APPOINTMENT',
  EDIT_APPOINTMENT_DETAILS_PAGE = 'EDIT_APPOINTMENT_DETAILS_PAGE',
  VIEW_CHOOSE_SUPERVISOR_PAGE = 'VIEW_CHOOSE_SUPERVISOR_PAGE',
  EDIT_CHOOSE_SUPERVISOR_PAGE = 'EDIT_CHOOSE_SUPERVISOR_PAGE',
  VIEW_APPOINTMENT_ATTENDANCE_OUTCOME_PAGE = 'VIEW_APPOINTMENT_ATTENDANCE_OUTCOME_PAGE',
  EDIT_APPOINTMENT_ATTENDANCE_OUTCOME_PAGE = 'EDIT_APPOINTMENT_ATTENDANCE_OUTCOME_PAGE',
  VIEW_APPOINTMENT_LOG_HOURS_PAGE = 'VIEW_APPOINTMENT_LOG_HOURS_PAGE',
  EDIT_APPOINTMENT_LOG_HOURS_PAGE = 'EDIT_APPOINTMENT_LOG_HOURS_PAGE',
  VIEW_APPOINTMENT_LOG_COMPLIANCE_PAGE = 'VIEW_APPOINTMENT_LOG_COMPLIANCE_PAGE',
  EDIT_APPOINTMENT_LOG_COMPLIANCE_PAGE = 'EDIT_APPOINTMENT_LOG_COMPLIANCE_PAGE',
  VIEW_APPOINTMENT_CONFIRM_PAGE = 'VIEW_APPOINTMENT_CONFIRM_PAGE',
  EDIT_APPOINTMENT = 'EDIT_APPOINTMENT',
  VIEW_SESSIONS_SEARCH_PAGE = 'VIEW_SESSIONS_SEARCH_PAGE',
  VIEW_SESSIONS = 'VIEW_SESSIONS',
  VIEW_SESSION_APPOINTMENTS = 'VIEW_SESSION_APPOINTMENTS',
  VIEW_PROJECTS_SEARCH_PAGE = 'VIEW_PROJECTS_SEARCH_PAGE',
  SEARCH_PROJECTS = 'SEARCH_PROJECTS',
  VIEW_INDIVIDUAL_PLACEMENTS = 'VIEW_INDIVIDUAL_PLACEMENTS',
  VIEW_COURSE_COMPLETIONS_SEARCH_PAGE = 'VIEW_COURSE_COMPLETIONS_SEARCH_PAGE',
  VIEW_COURSE_COMPLETIONS_UNABLE_TO_CREDIT_TIME_PAGE = 'VIEW_COURSE_COMPLETIONS_UNABLE_TO_CREDIT_TIME_PAGE',
  EDIT_COURSE_COMPLETIONS_UNABLE_TO_CREDIT_TIME_PAGE = 'EDIT_COURSE_COMPLETIONS_UNABLE_TO_CREDIT_TIME_PAGE',
  CREATE_COURSE_COMPLETION_APPOINTMENT = 'CREATE_COURSE_COMPLETION_APPOINTMENT',
  EDIT_COURSE_COMPLETION_APPOINTMENT = 'EDIT_COURSE_COMPLETION_APPOINTMENT',
  VIEW_COURSE_COMPLETION_FILTER = 'VIEW_COURSE_COMPLETION_FILTER',
  VIEW_COURSE_COMPLETIONS = 'VIEW_COURSE_COMPLETIONS',
  VIEW_COURSE_COMPLETION = 'VIEW_COURSE_COMPLETION',
  SEARCH_COURSE_COMPLETION_CRN = 'SEARCH_COURSE_COMPLETION_CRN',
  VIEW_CONFIRM_CRN_MATCH = 'VIEW_CONFIRM_CRN_MATCH',
  VIEW_COURSE_COMPLETION_REQUIREMENT = 'VIEW_COURSE_COMPLETION_REQUIREMENT',
  VIEW_COURSE_COMPLETION_PROJECT = 'VIEW_COURSE_COMPLETION_PROJECT',
  VIEW_COOKIES_POLICY_PAGE = 'VIEW_COOKIES_POLICY_PAGE',
  SEARCH_TRAVEL_TIME_TASKS = 'SEARCH_TRAVEL_TIME_TASKS',
  VIEW_TRAVEL_TIME_TASKS = 'VIEW_TRAVEL_TIME_TASKS',
  VIEW_APPOINTMENT_DETAILS_TRAVEL_TIME = 'VIEW_APPOINTMENT_DETAILS_TRAVEL_TIME',
  CREATE_ADJUSTMENT = 'CREATE_ADJUSTMENT',
  EDIT_TRAVEL_TIME_TASK_NOT_ELIGIBLE = 'EDIT_TRAVEL_TIME_TASK_NOT_ELIGIBLE',
  VIEW_SESSIONS_SELECT_PEOPLE = 'VIEW_SESSIONS_SELECT_PEOPLE',
  EDIT_SESSIONS_SELECT_PEOPLE = 'EDIT_SESSIONS_SELECT_PEOPLE',
}

export default class AuditService {
  constructor(private readonly auditClient: AuditClient) {}

  async sendAuditMessage(auditParams: AuditParams) {
    await this.auditClient.sendAuditMessage(auditParams)
  }
}
