import HmppsAuditClient, { AuditEvent } from '../data/hmppsAuditClient'

export enum Page {
  EXAMPLE_PAGE = 'EXAMPLE_PAGE',
  VIEW_INDEX_PAGE = 'VIEW_INDEX_PAGE',
  VIEW_APPOINTMENT = 'VIEW_APPOINTMENT',
  SUBMIT_APPOINTMENT_DETAILS_PAGE = 'SUBMIT_APPOINTMENT_DETAILS_PAGE',
  SHOW_CHOOSE_SUPERVISOR_PAGE = 'SHOW_CHOOSE_SUPERVISOR_PAGE',
  SUBMIT_CHOOSE_SUPERVISOR_PAGE = 'SUBMIT_CHOOSE_SUPERVISOR_PAGE',
  SHOW_APPOINTMENT_ATTENDANCE_OUTCOME_PAGE = 'SHOW_APPOINTMENT_ATTENDANCE_OUTCOME_PAGE',
  SUBMIT_APPOINTMENT_ATTENDANCE_OUTCOME_PAGE = 'SUBMIT_APPOINTMENT_ATTENDANCE_OUTCOME_PAGE',
  SHOW_APPOINTMENT_LOG_HOURS_PAGE = 'SHOW_APPOINTMENT_LOG_HOURS_PAGE',
  SUBMIT_APPOINTMENT_LOG_HOURS_PAGE = 'SUBMIT_APPOINTMENT_LOG_HOURS_PAGE',
  SHOW_APPOINTMENT_LOG_COMPLIANCE_PAGE = 'SHOW_APPOINTMENT_LOG_COMPLIANCE_PAGE',
  SUBMIT_APPOINTMENT_LOG_COMPLIANCE_PAGE = 'SUBMIT_APPOINTMENT_LOG_COMPLIANCE_PAGE',
  SHOW_APPOINTMENT_CONFIRM_PAGE = 'SHOW_APPOINTMENT_CONFIRM_PAGE',
  EDIT_APPOINTMENT = 'EDIT_APPOINTMENT',
  VIEW_SESSIONS_SEARCH_PAGE = 'VIEW_SESSIONS_SEARCH_PAGE',
  VIEW_SESSIONS = 'VIEW_SESSIONS',
  VIEW_SESSION_APPOINTMENTS = 'VIEW_SESSION_APPOINTMENTS',
  VIEW_PROJECTS_SEARCH_PAGE = 'VIEW_PROJECTS_SEARCH_PAGE',
  SEARCH_PROJECTS = 'SEARCH_PROJECTS',
  VIEW_INDIVIDUAL_PLACEMENTS = 'VIEW_INDIVIDUAL_PLACEMENTS',
  SHOW_COURSE_COMPLETIONS_SEARCH_PAGE = 'SHOW_COURSE_COMPLETIONS_SEARCH_PAGE',
  SHOW_SINGLE_COMPLETION_PAGE = 'SHOW_SINGLE_COMPLETION_PAGE',
  SHOW_COURSE_COMPLETIONS_UNABLE_TO_CREDIT_TIME_PAGE = 'SHOW_COURSE_COMPLETIONS_UNABLE_TO_CREDIT_TIME_PAGE',
  SUBMIT_COURSE_COMPLETIONS_UNABLE_TO_CREDIT_TIME_PAGE = 'SUBMIT_COURSE_COMPLETIONS_UNABLE_TO_CREDIT_TIME_PAGE',
  SUBMIT_COURSE_COMPLETIONS_CREATE_NEW_APPOINTMENT = 'SUBMIT_COURSE_COMPLETIONS_CREATE_NEW_APPOINTMENT',
  SHOW_COURSE_COMPLETIONS_SEARCH_PAGE_RESULTS = 'SHOW_COURSE_COMPLETIONS_SEARCH_PAGE_RESULTS',
  COOKIES_POLICY_PAGE = 'COOKIES_POLICY_PAGE',
  SEARCH_TRAVEL_TIME_TASKS = 'SEARCH_TRAVEL_TIME_TASKS',
  VIEW_TRAVEL_TIME_TASKS = 'VIEW_TRAVEL_TIME_TASKS',
  VIEW_APPOINTMENT_DETAILS_TRAVEL_TIME = 'VIEW_APPOINTMENT_DETAILS_TRAVEL_TIME',
  CREATE_ADJUSTMENT = 'CREATE_ADJUSTMENT',
  EDIT_TRAVEL_TIME_TASK_NOT_ELIGIBLE = 'EDIT_TRAVEL_TIME_TASK_NOT_ELIGIBLE',
}

export interface PageViewEventDetails {
  who: string
  subjectId?: string
  subjectType?: string
  correlationId?: string
  details?: object
}

export default class AuditService {
  readonly hmppsAuditClient: HmppsAuditClient

  constructor(hmppsAuditClient: HmppsAuditClient) {
    this.hmppsAuditClient = hmppsAuditClient
  }

  async logAuditEvent(event: AuditEvent) {
    await this.hmppsAuditClient.sendMessage(event)
  }

  async logPageView(page: Page, eventDetails: PageViewEventDetails) {
    const event: AuditEvent = {
      ...eventDetails,
      what: `PAGE_VIEW_${page}`,
    }
    await this.hmppsAuditClient.sendMessage(event)
  }
}
