import HmppsAuditClient, { AuditEvent } from '../data/hmppsAuditClient'

export enum Page {
  EXAMPLE_PAGE = 'EXAMPLE_PAGE',
  INDEX_PAGE = 'INDEX_PAGE',
  SHOW_APPOINTMENT_PROJECT_DETAILS_PAGE = 'SHOW_APPOINTMENT_PROJECT_DETAILS_PAGE',
  SUBMIT_APPOINTMENT_PROJECT_DETAILS_PAGE = 'SUBMIT_APPOINTMENT_PROJECT_DETAILS_PAGE',
  SHOW_APPOINTMENT_ATTENDANCE_OUTCOME_PAGE = 'SHOW_APPOINTMENT_ATTENDANCE_OUTCOME_PAGE',
  SUBMIT_APPOINTMENT_ATTENDANCE_OUTCOME_PAGE = 'SUBMIT_APPOINTMENT_ATTENDANCE_OUTCOME_PAGE',
  SHOW_APPOINTMENT_LOG_HOURS_PAGE = 'SHOW_APPOINTMENT_LOG_HOURS_PAGE',
  SUBMIT_APPOINTMENT_LOG_HOURS_PAGE = 'SUBMIT_APPOINTMENT_LOG_HOURS_PAGE',
  SHOW_APPOINTMENT_LOG_COMPLIANCE_PAGE = 'SHOW_APPOINTMENT_LOG_COMPLIANCE_PAGE',
  SUBMIT_APPOINTMENT_LOG_COMPLIANCE_PAGE = 'SUBMIT_APPOINTMENT_LOG_COMPLIANCE_PAGE',
  SHOW_APPOINTMENT_CONFIRM_PAGE = 'SHOW_APPOINTMENT_CONFIRM_PAGE',
  SUBMIT_APPOINTMENT_CONFIRM_PAGE = 'SUBMIT_APPOINTMENT_CONFIRM_PAGE',
  SHOW_SESSIONS_SEARCH_PAGE = 'SHOW_SESSIONS_SEARCH_PAGE',
  SHOW_SESSIONS_SEARCH_PAGE_RESULTS = 'SHOW_SESSIONS_SEARCH_PAGE_RESULTS',
  SHOW_SINGLE_SESSION_PAGE = 'SHOW_SINGLE_SESSION_PAGE',
  SHOW_SINGLE_PROJECT_PAGE = 'SHOW_SINGLE_PROJECT_PAGE',
}

export interface PageViewEventDetails {
  who: string
  subjectId?: string
  subjectType?: string
  correlationId?: string
  details?: object
}

export default class AuditService {
  constructor(private readonly hmppsAuditClient: HmppsAuditClient) {}

  async logAuditEvent(event: AuditEvent) {
    await this.hmppsAuditClient.sendMessage(event)
  }

  async logPageView(page: Page, eventDetails: PageViewEventDetails) {
    const event: AuditEvent = {
      ...eventDetails,
      what: `PAGE_VIEW_${page}`,
    }
    await this.hmppsAuditClient.sendMessage(event)
  }
}
