name: Seed projects, offenders and allocations

on:
  workflow_dispatch:
    inputs:
      seed_data_file:
        description: 'The seed data file to use'
        required: true
        default: 'seed_data.yml'
        type: choice
        options:
          - seed_data.yml
      node_version_file:
        description: 'Passed to setup-node action to specify where to source the version of node from'
        required: false
        type: string
        default: '.nvmrc'

permissions:
  contents: read

jobs:
  create-session-test-data:
    runs-on: [self-hosted, Linux, X64, hmpps-github-actions-runner]

    steps:
      - uses: actions/checkout@v6
        with:
          # Repository is specified to run the workflow from the API repository
          repository: 'ministryofjustice/hmpps-community-payback-ui'

      - name: Use Node.js ${{ inputs.node_version_file }}
        uses: actions/setup-node@v6
        with:
          node-version-file: ${{ inputs.node_version_file }}
          cache: npm

      - name: install dependencies
        shell: bash
        run: |
          npm run setup

      - name: install playwright
        shell: bash
        run: |
          npx playwright install

      - name: run seed data task
        env:
          DELIUS_USERNAME: ${{ secrets.DELIUS_USERNAME }}
          DELIUS_PASSWORD: ${{ secrets.DELIUS_PASSWORD }}
          DELIUS_URL: ${{ vars.DELIUS_URL }}
          SEED_DATA_PATH: "seed_data/${{ github.event.inputs.seed_data_file }}"
          TIMEOUT_INTERVAL: 3600000
        shell: bash
        run: |
          npx playwright test --project seedData
      - name: upload results
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: npm_e2e_test_artifacts
          path: |
            e2e-tests/test_results/
            e2e-tests/playwright-report/
